services:
  backend:
    build: ./quiz-api
    image: likian/quiz-backend:latest
    env_file:
      - ./quiz-api/.env
    ports:
      - "5000:5000"

  frontend:
    build: ./quiz-ui
    image: likian/quiz-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
